name: news_feed
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.4.0
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.1
  firebase_messaging: ^6.0.13
  provider: ^4.0.4
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+4
  date_format: ^1.0.8
  font_awesome_flutter: ^8.7.0
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2
  google_nav_bar: ^2.1.0
  flutter_local_notifications: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/


