name: news_feed
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  google_sign_in: ^4.4.0
  firebase_storage: ^4.0.0
  provider: ^4.0.4
  fluttertoast: ^7.0.4
  image_picker: ^0.6.3+4
  font_awesome_flutter: ^8.7.0
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2
  audio_recorder: ^1.0.2
  audioplayers: ^0.16.1
  intl: ^0.16.1
  permission_handler: ^5.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jpg"

flutter_native_splash:
  image: assets/images/signin.png
  color: "FFFFFF"
  fill: false
  android_disable_fullscreen: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/


